### PR TITLE
Replace the crypto module.

### PR DESCRIPTION
**Pull request by thiagofalencar**
Add the "create-hmac" dependency to the project, replacing the crypto, that was deprecated https://www.npmjs.com/package/crypto and replaced by a native node module.

### CODE REVIEW

**Comment by claudiosanches** [comment]
Looks like that is not so easy as changing the dependency: https://www.npmjs.com/package/create-hmac

**Comment by thiagofalencar** [comment]
If simple was replaced the dependency on require line, will break... because the word "crypto" now is a reserved as node module, and couldn't be used as a variable name. I tested...

**Comment by claudiosanches** [comment]
Ok, but for the module description looks like should replace JS code too in order to make it work.

**Comment by thiagofalencar** [comment]
Yeah man, you are right! I forgot of commit the index.js... I did now.

**Comment by vladggg** [comment]
please merge this man`s pull requests :) they are working

**Pull request merged**
